# --------------------------------------------------------------------------- #
# API Server Configuration
# --------------------------------------------------------------------------- #
# These settings control the behavior of the FastAPI backend server that
# provides a RESTful API for managing jobs and schedules.
# --------------------------------------------------------------------------- #
api:
  # The protocol scheme to use for the API server (e.g., http, https).
  scheme: http
  # The hostname or IP address to bind the API server to.
  # Use '0.0.0.0' to make it accessible from other machines on the network.
  host: 127.0.0.1
  # The port number for the API server.
  port: 8000

# --------------------------------------------------------------------------- #
# Web GUI Configuration
# --------------------------------------------------------------------------- #
# Settings for the Flask-based web user interface.
# --------------------------------------------------------------------------- #
webgui:
  # The protocol scheme for the web GUI (e.g., http, https).
  scheme: http
  # The hostname or IP address for the web GUI.
  host: 127.0.0.1
  # The port number for the web GUI.
  port: 5012

# --------------------------------------------------------------------------- #
# Core Application Settings
# --------------------------------------------------------------------------- #
core:
  # The database connection string.
  # For SQLite, use: 'sqlite:///your_database_file.sqlite'
  # For PostgreSQL, use: 'postgresql://user:password@host:port/database'
  database_url: "sqlite:///jobs.sqlite"

# --------------------------------------------------------------------------- #
# Scheduler Settings
# --------------------------------------------------------------------------- #
scheduler:
  # The base directory for shell command jobs.
  # Using '~' resolves to the user's home directory.
  # This acts as a sandbox for all shell commands.
  work_dir: "~/.task_schedule/work_list"

# --------------------------------------------------------------------------- #
# Development Settings
# --------------------------------------------------------------------------- #
development:
  # If true, jobs/workflows found in the database but NOT in the YAML files
  # will be deleted from the database during a YAML sync.
  # Set to false to allow jobs created via the UI to persist even if they
  # are not defined in the YAML files.
  delete_orphaned_jobs_on_sync: false